### ISSUE TITLE
Votes not populating for Massachusetts bills

### ISSUE THREAD

**Issue by zdalexander512** [openstates/documentation#2]
![votes](https://cloud.githubusercontent.com/assets/17784654/22938280/53768928-f2a9-11e6-9f01-d947d5874cf4.PNG)

Is there a way for me to access this vote information for Massachusetts?

**Comment by mileswwatkins** [comment]
@zdalexander512, can you repost this issue in the main repo? This repo is just the documentation for the project. https://github.com/openstates/openstates

**Comment by mileswwatkins** [comment]
This also seems relevant: https://github.com/openstates/openstates/issues/1162
