### ISSUE TITLE
Misleading VoteEvent constructor comment in pupa conversion, creates validation issues.

### ISSUE THREAD

**Issue by brymut** [openstates/documentation#27]
Hi, small issue with the pupa conversion documentation. I recently came across it when trying to convert the old billy Vote to the new pupa VoteEvent object, more specifically the result instance variable of the VoteEvent object. 

On https://github.com/openstates/documentation/blob/master/contributing/pupa-conversion-2.rst line 298, the result variable is referred to as a Boolean value. When I ran the scrapper a ValidationError was raised (stack trace below). 

```
validictory.validator.ValidationError: validation of VoteEvent 6755957a-10cb-11e7-9b11-0242ac120004 failed: 2 validation errors:
Value True for field '<obj>.result' is not of type string
Value True for field '<obj>.result' is not in the enumeration: ['pass', 'fail']

```

I think the comment should be removed and perhaps indicate that it should be string value of either 'pass' or 'fail' as described by the ValidationError message.

**Comment by brymut** [comment]
I know its not really an issue, anyone can probably figure out the problem, and probably a waste of time, but I'd be more than happy to handle making the pull request. Shouldn't take long.

**Comment by jamesturk** [comment]
Ah yes, if you have a chance to make a quick PR that'd be great :)

**Comment by brymut** [comment]
Alright, created the pull request. Thanks, @jamesturk.
