### ISSUE TITLE
Possible to check for updates to a Bill?

### ISSUE THREAD

**Issue by brylie** [openstates/documentation#45]
We are [integrating OpenStates into CiviWiki](https://github.com/CiviWiki/OpenCiviWiki/issues/13). We are considering how to 'cache' OpenStates data, to reduce the amount of network requests. Are there methods on the OpenStates endpoints that would allow us to see whether a Bill, or other document, has been updated since a given date?

**Comment by jamesturk** [comment]
you can use the ``updated_since`` parameter (see http://docs.openstates.org/en/latest/api/bills.html#bills) to only get things that have updated

**Comment by jamesturk** [comment]
closing this, but let me know if that doesn't answer it
