### ISSUE TITLE
Representative for 56th district in ME is incorrect

### ISSUE THREAD

**Issue by yocheved** [openstates/documentation#48]
It's listed here as "Gina M. Mason" when really she died on September 5, 2017 and the current Rep is "Richard Mason".
sources:
https://ballotpedia.org/Gina_Mason
https://ballotpedia.org/Richard_Mason
Please update this in your database

**Comment by mileswwatkins** [comment]
Moving this issue to the `openstates/openstates` repository, which is where data issues are best reported. Thanks for the catch, though, @yocheved!

https://github.com/openstates/openstates/issues/2154
