### ISSUE TITLE
Outdated Infrastructure Overview?

### ISSUE THREAD

**Issue by jmillxyz** [openstates/documentation#53]
Hi! I'm new so I may be missing something.

In the [infrastrucutre overview](http://docs.openstates.org/en/latest/infrastructure/index.html) it looks like the docs reference the billy project, but I'm unsure how pupa is related to all of this -- do they do the same thing?

Also, if there's a better way to get up and running without opening up issues, please let me know! :)

**Comment by jamesturk** [comment]
definitely outdated- I'll try to write up a newer version soon
